- name: Install Redis
  action: apt pkg=redis-server state=present
    
- name: Don't start Redis on boot
  action: service name=redis-server state=stopped enabled=no

- name: Copy Redis configuration
  action: copy src=redis.conf dest=/etc/redis/redis.conf
    
- name: Add Redis to Monit
  action: copy src=redis.monit dest=/etc/monit/conf.d/redis.monit
    
- name: Reload Monit
  action: service name=monit state=reloaded
    
- name: Start Redis with Monit
  action: monit name=redis-server state=started
