- name: Install python-software-properties.
  action: apt pkg=python-software-properties state=present

- name: Install monit
  action: apt pkg=monit state=present
    
- name: Copy monit config
  action: copy src=monitrc dest=/etc/monit/monitrc

