---
- name: discourse | create sync project directory
  file: path=/home/discourse/sync
        state=directory
        owner=discourse
        group=discourse

- name: discourse | copy sync project over
  copy: dest=/home/discourse/sync/
        src=$item
        owner=discourse
        group=discourse
  with_fileglob:
  - ./sync/*
  register: project

- name: discourse | bundle install sync
  shell: /bin/bash --login -c "cd /home/discourse/discourse && bundle install"

- name: discourse | copy sync monit config
  copy: src=monit dest=/etc/monit/conf.d/sync
  register: monit_config

- name: discourse | restart monit
  service: name=monit state=restarted
  when: monit_config.changed

- name: discourse | restart sync
  shell: monit restart sync
  when: project.changed

