development:
  adapter: postgresql
  database: hummingbird_development
  host: localhost

test:
  adapter: postgresql
  database: hummingbird_test
  host: localhost

production:
  adapter: postgresql
  database: hummingbird_production
  username: hummingbird
  password: TheBoilingPointOfCarbonDioxide
  host: localhost
  pool: 50
