development:
  adapter: postgresql
  database: hummingbird_development
  host: <%= ENV['POSTGRES_HOST'] %>
  port: 5432

test:
  adapter: postgresql
  database: hummingbird_test
  host: localhost

production:
  adapter: postgresql
  database: hummingbird_production
  username: hummingbird
  password: TheBoilingPointOfCarbonDioxide
  host: <%= ENV['POSTGRES_HOST'] %>
  port: 5432
  pool: 50
