production:
  solr:
    hostname: ENV['SOLR_HOST']
    port: 8080
    log_level: WARNING
    path: '/solr/hummingbird/'
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: ENV['SOLR_HOST']
    port: 8982
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
