- name: Install HAProxy
  apt: pkg=haproxy state=present

- name: Don't start HAProxy on boot.
  service: name=haproxy state=stopped enabled=no

- name: Copy HAProxy configuration.
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  register: haproxy_config

- name: Add HAProxy to Monit
  copy: src=haproxy.monit dest=/etc/monit/conf.d/haproxy.monit
  register: haproxy_monit_config

- name: Reload Monit
  service: name=monit state=reloaded
  when: haproxy_monit_config.changed

- name: Restart HAProxy if needed.
  shell: kill `cat /var/run/haproxy.pid` && monit start haproxy
  when: haproxy_config.changed
