- name: Add Postgres Apt signing key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: Copy Postgres repository source file
  template: src=pgdg.list dest=/etc/apt/sources.list.d/pgdg.list

- name: Install Postgres packages
  apt: pkg=$item state=present update_cache=yes
  with_items:
  - pgdg-keyring
  - postgresql-9.2
  - libpq5
  - libpq-dev
  - postgresql-contrib-9.2
  - python-psycopg2

- name: Change postgres user password
  action: user name=postgres password={{postgres_password}}

- name: Create backups directory structure
  file: path=$item state=directory owner=postgres
  with_items:
  - /home/vikhyat/pg_backups
  - /home/vikhyat/pg_backups/daily
  - /home/vikhyat/pg_backups/hourly

- cron: name="daily pg backup" 
        hour=2 minute=50 user="postgres" 
        job='pg_dumpall | gzip > /home/vikhyat/pg_backups/daily/$(date "+\%Y_\%m_\%d-\%H_\%M_\%S.sql.gz")'

- cron: name="hourly pg backup" 
        minute=20 user="postgres" 
        job='pg_dumpall | gzip > /home/vikhyat/pg_backups/hourly/$(date "+\%Y_\%m_\%d-\%H_\%M_\%S.sql.gz")'

