- name: Add nginx repository
  action: apt_repository repo=ppa:nginx/stable state=present
  register: add_nginx_ppa
    
- name: Update package cache
  action: apt update_cache=yes
  only_if: ${add_nginx_ppa.changed}

- name: Install nginx
  action: apt pkg=nginx state=latest
    
- name: Start nginx
  service: name=nginx state=started
    
- name: Install imagemagick for paperclip
  action: apt pkg=imagemagick state=present

- name: Add Unicorn to Monit
  action: copy src=unicorn.monit dest=/etc/monit/conf.d/unicorn.monit
  register: unicorn_monit_config

- name: Reload Monit
  action: service name=monit state=reloaded
  only_if: ${unicorn_monit_config.changed}

- name: Start unicorn with Monit
  action: monit name=unicorn state=started

- name: Copy main nginx config
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
    
- name: Copy nginx config files
  template: src=frontend.nginx.conf dest=/etc/nginx/sites-enabled/hummingbird
  register: frontend_nginx_conf
    
- name: Remove nginx default site
  action: file path=/etc/nginx/sites-enabled/default state=absent

- name: Reload Nginx
  action: service name=nginx state=reloaded
  only_if: ${frontend_nginx_conf.changed}
