- name: Install Postfix
  apt: pkg=postfix state=present

- name: Copy main.cf
  copy: src=main.cf dest=/etc/postfix/main.cf

- name: Copy virtual map file
  copy: src=virtual dest=/etc/postfix/virtual
  register: virtual

- name: Reload virtual map file
  shell: postmap /etc/postfix/virtual && service postfix reload
  only_if: ${virtual.changed}

- name: Install nodejs and npm
  apt: pkg=$item state=present
  with_items:
  - nodejs
  - npm

- name: Install Haraka
  npm: name=$item global=yes
  with_items:
  - Haraka
  - daemon

- name: Copy Haraka config
  sudo: False
  local_action: command rsync -e ssh -a --delete roles/mail/files/haraka-outbound vikhyat@{{inventory_hostname}}:/home/vikhyat/haraka
  register: haraka_config

- name: Create queue directory
  file: path=/home/vikhyat/haraka/haraka-outbound/queue
        state=directory

- name: Copy Haraka monit config
  copy: src=haraka.monit dest=/etc/monit/conf.d/haraka.monit

- name: Reload monit
  service: name=monit state=reloaded

- name: Start Haraka with Monit
  monit: name=haraka-outbound state=restarted
